parameters:
  app.response_headers:
    Referrer-Policy: strict-origin-when-cross-origin

    # Remember to register the domain on https://hstspreload.org/ or preload will not work.
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

    X-Content-Type-Options: nosniff
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
